### ISSUE TITLE
Microservice can't connect to seed

### ISSUE THREAD

**Issue by skolomiiets** [scalecube/scalecube-seed#9]
Microservice trying to connect to seed:

    D 2018-12-24T11:57:04,940 i.s.c.m.MembershipProtocolImpl Send Sync to seed:4801: Message {headers: {q=sc/membership/sync, cid=null}, sender: 100.106.0.4:42817, data: SyncData{membership=[{m: 7CE27F8F9EB8C3D0B27F@100.106.0.4:42817/125054601, s: ALIVE, inc: 0}], syncGroup=default}} [sc-cluster-42817-1]
    D 2018-12-24T11:57:04,941 r.n.c.BootstrapHandlers [id: 0xa7cb042e] Initialized pipeline DefaultChannelPipeline{(BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (LengthFieldPrepender#0 = io.netty.handler.codec.LengthFieldPrepender), (ExceptionHandler#0 = io.scalecube.transport.ExceptionHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)} [sc-cluster-io-epoll-2]
    D 2018-12-24T11:57:04,943 r.n.r.NewConnectionProvider [id: 0xa7cb042e, L:/100.106.0.4:34244 - R:seed/100.65.210.197:4801] Connected new channel [sc-cluster-io-epoll-2]
    D 2018-12-24T11:57:04,943 r.n.r.NewConnectionProvider [id: 0xa7cb042e, L:/100.106.0.4:34244 - R:seed/100.65.210.197:4801] onStateChange([connected], SimpleConnection{channel=[id: 0xa7cb042e, L:/100.106.0.4:34244 - R:seed/100.65.210.197:4801]}) [sc-cluster-io-epoll-2]
    D 2018-12-24T11:57:04,943 r.n.r.NewConnectionProvider [id: 0xa7cb042e, L:/100.106.0.4:34244 - R:seed/100.65.210.197:4801] onStateChange([configured], ChannelOperations{SimpleConnection{channel=[id: 0xa7cb042e, L:/100.106.0.4:34244 - R:seed/100.65.210.197:4801]}}) [sc-cluster-io-epoll-2]
    D 2018-12-24T11:57:04,943 r.n.c.ChannelOperationsHandler [id: 0xa7cb042e, L:/100.106.0.4:34244 - R:seed/100.65.210.197:4801] New sending options [sc-cluster-io-epoll-2]
    D 2018-12-24T11:57:04,943 r.n.c.ChannelOperationsHandler [id: 0xa7cb042e, L:/100.106.0.4:34244 - R:seed/100.65.210.197:4801] Writing object  [sc-cluster-io-epoll-2]
    D 2018-12-24T11:57:04,944 i.s.t.TransportImpl Connected to seed:4801: [id: 0xa7cb042e, L:/100.106.0.4:34244 - R:seed/100.65.210.197:4801] [sc-cluster-io-epoll-2]
    W 2018-12-24T11:57:04,944 i.s.t.ExceptionHandler Exception caught for channel [id: 0xa7cb042e, L:/100.106.0.4:34244 - R:seed/100.65.210.197:4801], syscall:read(..) failed: Connection reset by peer [sc-cluster-io-epoll-2]
    io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[netty-transport-native-unix-common-4.1.31.Final.jar:4.1.31.Final]
    D 2018-12-24T11:57:04,944 r.n.r.NewConnectionProvider [id: 0xa7cb042e, L:/100.106.0.4:34244 ! R:seed/100.65.210.197:4801] onStateChange([disconnecting], ChannelOperations{SimpleConnection{channel=[id: 0xa7cb042e, L:/100.106.0.4:34244 ! R:seed/100.65.210.197:4801]}}) [sc-cluster-io-epoll-2]
    D 2018-12-24T11:57:04,945 i.s.t.TransportImpl Disconnected from: seed:4801 [id: 0xa7cb042e, L:/100.106.0.4:34244 ! R:seed/100.65.210.197:4801] [sc-cluster-io-epoll-2]
    D 2018-12-24T11:57:06,552 c.c.c.c.c.ConfigurationProvider Received signal to proactively refresh (a maybe outdated) configuration. [cb-computations-3]

**Comment by segabriel** [comment]
Fixes for the following:
https://github.com/scalecube/scalecube-organization-service/pull/54
https://github.com/scalecube/scalecube-configuration-service/pull/49

PS: please specify which microservices can't be connected to the seed.
